language: java

jdk: 
- oraclejdk8

notifications:
    email: false

sudo: false

before_install:
- mkdir -p ~/.ant/lib
- chmod a+x wpilib.sh
- ./wpilib.sh

install:
- cp wpilib/ant/*.jar ~/.ant/lib

script: ant -f travis.xml

